### ISSUE TITLE
Restore clipboard content after QuickCursor has done its deed

### ISSUE THREAD

**Issue by kkaefer** [jessegrosjean/quickcursor#18]
Unfortunately, QuickCursor constantly overwrites my clipboard content because it uses it to copy the contents. It would be good to restore the contents right after it is done copying the text over or back.

**Comment by jessegrosjean** [comment]
It can be problematic, but I think I like the way that it works now. My logic is:

QuickCursor works (in part) by automating Select All / Copy and Paste. I could try to be smart and replace clipboard content, but doing that is sorta hiding the way that QuickCursor actually works. I think it's best to just keep things as simple as possible, since QuickCursor is already a bit confusing. It also is a good backup plan, because if something goes wrong (for example the source application doesn't accept the paste back into it) then your edited text isn't lost, it's still on the clipboard.

**Comment by kkaefer** [comment]
Putting the text in the clipboard when saving/closing the editor perfectly fine. I'm talking about the first copy action, i.e. when start editing.
