### ISSUE TITLE
RQ: Should switch back to original app after saving; possible?

### ISSUE THREAD

**Issue by subtleGradient** [jessegrosjean/quickcursor#2]
When you save and close the document. is there any way to make t switch back to the original app/window you were in when you started editing?

thanks double-much!

**Comment by jessegrosjean** [comment]
I think I'm not going to do this for now. I agree that it could be useful sometimes, but I think it would just be confusing at other times. I think if you quit the "editor" app then you should already switch back to the original app by default. So that already covers the simple case. In other cases I think it might just be confusing to automatically switch back to the original app. I'd rather just let the user be in control of doing that.

**Comment by subtleGradient** [comment]
Could it be a non-default preference or something.
The Edit in TextMate inputmanager switches back by default and nobody has ever complained about it.

I only beg because I don't know how to make it happen myself ;)

**Comment by jessegrosjean** [comment]
Thanks, I changed my mind, this feature is now in the current release.

**Comment by subtleGradient** [comment]
sweet!
thanks so very much. totally awesomizes my life.
